### ISSUE TITLE
Broken filtering (+ broken link in the docs)

### ISSUE THREAD

**Issue by doplumi** [Kinto/kinto-http.js#129]
There is a broken link in the docs. At https://www.npmjs.com/package/kinto-http#generic-options-for-list-operations the "what's supported" link gives 404 because it tries to access http://kinto.readthedocs.io/en/stable/core/api/resource.html#filtering.

There is a  http://kinto.readthedocs.io/en/stable/core/resource.html page (without /api/), but it doesn't have any #filtering element.

***
I was looking for filtering documentation because when I try to
`collection.listRecords({ filters: { id: ['id1', 'id2'] } })`
I get empty results, but when I try 
`collection.listRecords({ filters: { id: ['id1']  } })` 
and 
`collection.listRecords({ filters: { id: ['id2'] } })`
I get 1 result both times. In this case, shouldn't the first snippet return both records? 

I tried this on a different collection with a different property (to exclude some bug with 'id's), and I get same buggy result.

**Comment by glasserc** [comment]
Ugh, that documentation link should probably point instead to http://kinto.readthedocs.io/en/stable/api/1.x/filtering.html.

It seems from https://github.com/Kinto/kinto-http.js/blob/master/src/utils.js#L91-L93 that this query will turn into something like `id=id1&id=id2`. Since no record has both id=id1 and id=id2, you get an empty result. Unfortunately, it seems like there's no way to generate the correct query `in_id=id1,id2`. Passing an array will still get you `in_id=id1&in_id=id2`. This is certainly a bug -- there should be some way to express that.

**Comment by doplumi** [comment]
I checked for `qsify` usages in the code, and noticed it's only called on https://github.com/Kinto/kinto-http.js/blob/master/src/base.js#L383-L388.
So I forked the repo, fixed qsify and modified a couple of related tests. Filtering problem is gone 🙌

I'm going to use the new build in the evening agains a kinto server and follow up with a PR tomorrow in the morning.

Thank you @glasserc 🖐

**Comment by doplumi** [comment]
Just sent the PR to fix the filtering issue as #134.
Don't know where the docs are, so I can't fix the broken link. Are they on github?

**Comment by n1k0** [comment]
Thanks! Docs on npm are the README :)

**Comment by n1k0** [comment]
Released in [v2.4.1](https://github.com/Kinto/kinto-http.js/releases/tag/v2.4.1).
