### ISSUE TITLE
How do I get the body of an error with kinto-http.js?

### ISSUE THREAD

**Issue by Natim** [Kinto/kinto-http.js#235]
I have error.response but I don't know how to get the body:

https://github.com/Kinto/kinto-http.js/blob/master/src/http.js#L107-L112

**Comment by glasserc** [comment]
This error-handling part of the library is kind of complicated/weird. If we hit [this code path](https://github.com/Kinto/kinto-http.js/blob/master/src/http.js#L131-L134), we store the JSON data in an exception, which we then immediately discard at the catch block you linked to. If we don't hit that code path (for instance, because JSON parsing fails), then we don't appear to store the text anywhere. I don't think the current behavior is correct and I would be happy to review a PR to straighten it out.

See also https://bugzilla.mozilla.org/show_bug.cgi?id=1388830.

**Comment by glasserc** [comment]
Another important thing to do here would be to check for a backoff header, even in the case of (even unparseable) errors.

**Comment by glasserc** [comment]
If you catch a `ServerResponse`, the JSON body is available as `error.data`.

We check for backoff headers before examining the content of the response.
