### ISSUE TITLE
Kinto is not defined with version 4.4.0

### ISSUE THREAD

**Issue by vladikoff** [Kinto/kinto-http.js#259]
cc @Natim @glasserc 

Hey, I had to lock to 4.3.4 in the Notes PR: https://github.com/mozilla/notes/pull/313/commits/f9257c89fc07afa90a759a736324d2ad41da49b3

Otherwise it just throw `Kinto is not defined` with 4.4.0

![image](https://user-images.githubusercontent.com/128755/32922859-5d331a26-cb02-11e7-80b1-d5bf8a552b26.png)

**Comment by glasserc** [comment]
Hmm. I think this is because of https://github.com/Kinto/kinto-http.js/pull/255. We no longer unconditionally require babel-polyfill, but try to ensure that it isn't included twice. That's just a copy of a similar change that was made a long time ago to kinto.js: https://github.com/Kinto/kinto.js/pull/381/. babel-polyfill is only listed as a dev dependency in kinto-http.js, but a real dependency in kinto.js. I have to say this JS packaging stuff is a bit beyond me, but I can try to figure it out tomorrow.

**Comment by glasserc** [comment]
Could you try with v4.4.1?

**Comment by vladikoff** [comment]
@glasserc Fixed!! I unlocked the dependency in our new sync-v5 branch 👍  Thank you so much!
