### ISSUE TITLE
Should we shim other browser dependencies?

### ISSUE THREAD

**Issue by glasserc** [Kinto/kinto-http.js#470]
@ncloudioj raised (in #468) the point that we don't support `Blob` (which is part of the Web platform), which makes it difficult to use this library in Node. That was easy to fix, but there remain other requirements that we don't shim. Should we? Should this be the responsibility of the caller? I have no idea what the "done thing" is so I'm open to suggestions.

**Comment by dstaley** [comment]
The difficulty is making sure that any polyfills don't find their way into browser bundles. One way to make sure of is is to use Rollup to create a node-specific bundle, rewriting global uses of things like `fetch`, `btoa`, and `FormData` to their node-polyfill equivalents. This would be very easy with Rollup's inject plugin, but could potentially complicate using the library in a node project along with a bundler/builder that doesn't load the CommonJS version of the library. However in those circumstances it's likely possible for the user to configure their bundler to load the CommonJS version explicitly, so I think it's a worthwhile tradeoff. Furthermore I think the number of users using kinto-http in a node project along with a bundler is a very small group.

So, my suggestion would be to update the TypeScript/Rollup PR to use Rollup to build the CommonJS bundle, rewriting uses of the globals specified in `setup-jsdom.js` to their node polyfills.

**Comment by dstaley** [comment]
Adding in a new note since I've just burned myself on this issue. `kinto-http` relies on some browser-only things like `FormData` and `Headers` (even using things like `instance of Headers`). Polyfilling in the global scope alleviates any issues, but it might be good to make sure the library itself handles libraries like those in an environment-agnostic way.

That being said, I don't think we should polyfill language features. This just applies to APIs that are browser-only and will remain so.

**Comment by ncloudioj** [comment]
Sounds good to me. We ended up with some other ways to interact with the RS back-end instead of using the Node scripts, so this won't affect our daily tasks with RS any way.

@dstaley Thanks for investigating this! Feel free to close it.

**Comment by dstaley** [comment]
Continuing the discussion started by #678: 

The way I see it, there's three possible solutions:

## 1. What we're doing now

Continue doing what we're doing, and require Node consumers to polyfill things like `fetch` and `FormData` in the global scope. We can recommend libraries in the README, but consumers could use anything that conforms to the interface.

## 2. Provide an easily-importable polyfill

As a slightly nicer alternative, we could provide an easily-importable polyfill (`import 'kinto-http/polyfill'`) that provides the recommended polyfills. This would be easier for consumers, but would still require editing the global scope.

## 3. Create a bundle for Node

We could use Rollup to create a bundle for Node that rewrites the expected APIs with the polyfill equivalents. This moves the responsibility for creating the code that will run in Node from the TypeScript compiler to Rollup (along with the TypeScript compiler through a plugin). This would require [an additional Rollup plugin](https://github.com/rollup/plugins/tree/master/packages/inject) to provide the rewrite capabilities. With this solution Node would run a Rollup bundle while tools like Rollup and Webpack would pick-up the unbundled code when building browser bundles. Additionally, this would require no modifications to the source code since it's just tweaking the Rollup config.

## Suggestion

At some point during the development of the TypeScript version, I actually implemented the third solution where we rewrote global instances of libraries to the Node versions. It works reasonably well, and also doesn't require massive modifications nor does it confused the TypeScript compiler. If we don't want consumers to have to polyfill things in the global scope, I think creating a Node bundle would be a good solution.

@leplatrem what do you think?

**Comment by leplatrem** [comment]
I trust you on the decision for this :peace_symbol: 

If you already have Solution #3 implemented, and you would be willing to maintain it, then I believe it's the relevant decision. Also, Node is not our primary target, so if one day this Rollup approach breaks, then I find it acceptable for Node users (ping @ncloudioj!) to dig into it and fix it :) 

Thanks for your dedication and for being so thorough :pray:
